// source: crud/query.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var cosmos_base_query_v1beta1_pagination_pb = require('../cosmos/base/query/v1beta1/pagination_pb.js');
goog.object.extend(proto, cosmos_base_query_v1beta1_pagination_pb);
var crud_CrudValue_pb = require('../crud/CrudValue_pb.js');
goog.object.extend(proto, crud_CrudValue_pb);
goog.exportSymbol('proto.bluzelle.curium.crud.QueryAllCrudValueRequest', null, global);
goog.exportSymbol('proto.bluzelle.curium.crud.QueryAllCrudValueResponse', null, global);
goog.exportSymbol('proto.bluzelle.curium.crud.QueryGetCrudValueRequest', null, global);
goog.exportSymbol('proto.bluzelle.curium.crud.QueryGetCrudValueResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bluzelle.curium.crud.QueryGetCrudValueRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bluzelle.curium.crud.QueryGetCrudValueRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bluzelle.curium.crud.QueryGetCrudValueRequest.displayName = 'proto.bluzelle.curium.crud.QueryGetCrudValueRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bluzelle.curium.crud.QueryGetCrudValueResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bluzelle.curium.crud.QueryGetCrudValueResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bluzelle.curium.crud.QueryGetCrudValueResponse.displayName = 'proto.bluzelle.curium.crud.QueryGetCrudValueResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bluzelle.curium.crud.QueryAllCrudValueRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bluzelle.curium.crud.QueryAllCrudValueRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bluzelle.curium.crud.QueryAllCrudValueRequest.displayName = 'proto.bluzelle.curium.crud.QueryAllCrudValueRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bluzelle.curium.crud.QueryAllCrudValueResponse.repeatedFields_, null);
};
goog.inherits(proto.bluzelle.curium.crud.QueryAllCrudValueResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bluzelle.curium.crud.QueryAllCrudValueResponse.displayName = 'proto.bluzelle.curium.crud.QueryAllCrudValueResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bluzelle.curium.crud.QueryGetCrudValueRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.bluzelle.curium.crud.QueryGetCrudValueRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bluzelle.curium.crud.QueryGetCrudValueRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.crud.QueryGetCrudValueRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    uuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    key: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bluzelle.curium.crud.QueryGetCrudValueRequest}
 */
proto.bluzelle.curium.crud.QueryGetCrudValueRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bluzelle.curium.crud.QueryGetCrudValueRequest;
  return proto.bluzelle.curium.crud.QueryGetCrudValueRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bluzelle.curium.crud.QueryGetCrudValueRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bluzelle.curium.crud.QueryGetCrudValueRequest}
 */
proto.bluzelle.curium.crud.QueryGetCrudValueRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUuid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bluzelle.curium.crud.QueryGetCrudValueRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bluzelle.curium.crud.QueryGetCrudValueRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bluzelle.curium.crud.QueryGetCrudValueRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.crud.QueryGetCrudValueRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string uuid = 1;
 * @return {string}
 */
proto.bluzelle.curium.crud.QueryGetCrudValueRequest.prototype.getUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bluzelle.curium.crud.QueryGetCrudValueRequest} returns this
 */
proto.bluzelle.curium.crud.QueryGetCrudValueRequest.prototype.setUuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string key = 2;
 * @return {string}
 */
proto.bluzelle.curium.crud.QueryGetCrudValueRequest.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.bluzelle.curium.crud.QueryGetCrudValueRequest} returns this
 */
proto.bluzelle.curium.crud.QueryGetCrudValueRequest.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bluzelle.curium.crud.QueryGetCrudValueResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bluzelle.curium.crud.QueryGetCrudValueResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bluzelle.curium.crud.QueryGetCrudValueResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.crud.QueryGetCrudValueResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    crudvalue: (f = msg.getCrudvalue()) && crud_CrudValue_pb.CrudValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bluzelle.curium.crud.QueryGetCrudValueResponse}
 */
proto.bluzelle.curium.crud.QueryGetCrudValueResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bluzelle.curium.crud.QueryGetCrudValueResponse;
  return proto.bluzelle.curium.crud.QueryGetCrudValueResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bluzelle.curium.crud.QueryGetCrudValueResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bluzelle.curium.crud.QueryGetCrudValueResponse}
 */
proto.bluzelle.curium.crud.QueryGetCrudValueResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new crud_CrudValue_pb.CrudValue;
      reader.readMessage(value,crud_CrudValue_pb.CrudValue.deserializeBinaryFromReader);
      msg.setCrudvalue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bluzelle.curium.crud.QueryGetCrudValueResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bluzelle.curium.crud.QueryGetCrudValueResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bluzelle.curium.crud.QueryGetCrudValueResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.crud.QueryGetCrudValueResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCrudvalue();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      crud_CrudValue_pb.CrudValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional CrudValue CrudValue = 1;
 * @return {?proto.bluzelle.curium.crud.CrudValue}
 */
proto.bluzelle.curium.crud.QueryGetCrudValueResponse.prototype.getCrudvalue = function() {
  return /** @type{?proto.bluzelle.curium.crud.CrudValue} */ (
    jspb.Message.getWrapperField(this, crud_CrudValue_pb.CrudValue, 1));
};


/**
 * @param {?proto.bluzelle.curium.crud.CrudValue|undefined} value
 * @return {!proto.bluzelle.curium.crud.QueryGetCrudValueResponse} returns this
*/
proto.bluzelle.curium.crud.QueryGetCrudValueResponse.prototype.setCrudvalue = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bluzelle.curium.crud.QueryGetCrudValueResponse} returns this
 */
proto.bluzelle.curium.crud.QueryGetCrudValueResponse.prototype.clearCrudvalue = function() {
  return this.setCrudvalue(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bluzelle.curium.crud.QueryGetCrudValueResponse.prototype.hasCrudvalue = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.bluzelle.curium.crud.QueryAllCrudValueRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bluzelle.curium.crud.QueryAllCrudValueRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.crud.QueryAllCrudValueRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    uuid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    pagination: (f = msg.getPagination()) && cosmos_base_query_v1beta1_pagination_pb.PageRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bluzelle.curium.crud.QueryAllCrudValueRequest}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bluzelle.curium.crud.QueryAllCrudValueRequest;
  return proto.bluzelle.curium.crud.QueryAllCrudValueRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bluzelle.curium.crud.QueryAllCrudValueRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bluzelle.curium.crud.QueryAllCrudValueRequest}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUuid(value);
      break;
    case 2:
      var value = new cosmos_base_query_v1beta1_pagination_pb.PageRequest;
      reader.readMessage(value,cosmos_base_query_v1beta1_pagination_pb.PageRequest.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bluzelle.curium.crud.QueryAllCrudValueRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bluzelle.curium.crud.QueryAllCrudValueRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.crud.QueryAllCrudValueRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUuid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cosmos_base_query_v1beta1_pagination_pb.PageRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional string uuid = 1;
 * @return {string}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueRequest.prototype.getUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.bluzelle.curium.crud.QueryAllCrudValueRequest} returns this
 */
proto.bluzelle.curium.crud.QueryAllCrudValueRequest.prototype.setUuid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional cosmos.base.query.v1beta1.PageRequest pagination = 2;
 * @return {?proto.cosmos.base.query.v1beta1.PageRequest}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueRequest.prototype.getPagination = function() {
  return /** @type{?proto.cosmos.base.query.v1beta1.PageRequest} */ (
    jspb.Message.getWrapperField(this, cosmos_base_query_v1beta1_pagination_pb.PageRequest, 2));
};


/**
 * @param {?proto.cosmos.base.query.v1beta1.PageRequest|undefined} value
 * @return {!proto.bluzelle.curium.crud.QueryAllCrudValueRequest} returns this
*/
proto.bluzelle.curium.crud.QueryAllCrudValueRequest.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bluzelle.curium.crud.QueryAllCrudValueRequest} returns this
 */
proto.bluzelle.curium.crud.QueryAllCrudValueRequest.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueRequest.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bluzelle.curium.crud.QueryAllCrudValueResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bluzelle.curium.crud.QueryAllCrudValueResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    crudvalueList: jspb.Message.toObjectList(msg.getCrudvalueList(),
    crud_CrudValue_pb.CrudValue.toObject, includeInstance),
    pagination: (f = msg.getPagination()) && cosmos_base_query_v1beta1_pagination_pb.PageResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bluzelle.curium.crud.QueryAllCrudValueResponse}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bluzelle.curium.crud.QueryAllCrudValueResponse;
  return proto.bluzelle.curium.crud.QueryAllCrudValueResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bluzelle.curium.crud.QueryAllCrudValueResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bluzelle.curium.crud.QueryAllCrudValueResponse}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new crud_CrudValue_pb.CrudValue;
      reader.readMessage(value,crud_CrudValue_pb.CrudValue.deserializeBinaryFromReader);
      msg.addCrudvalue(value);
      break;
    case 2:
      var value = new cosmos_base_query_v1beta1_pagination_pb.PageResponse;
      reader.readMessage(value,cosmos_base_query_v1beta1_pagination_pb.PageResponse.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bluzelle.curium.crud.QueryAllCrudValueResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bluzelle.curium.crud.QueryAllCrudValueResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCrudvalueList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      crud_CrudValue_pb.CrudValue.serializeBinaryToWriter
    );
  }
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cosmos_base_query_v1beta1_pagination_pb.PageResponse.serializeBinaryToWriter
    );
  }
};


/**
 * repeated CrudValue CrudValue = 1;
 * @return {!Array<!proto.bluzelle.curium.crud.CrudValue>}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.prototype.getCrudvalueList = function() {
  return /** @type{!Array<!proto.bluzelle.curium.crud.CrudValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, crud_CrudValue_pb.CrudValue, 1));
};


/**
 * @param {!Array<!proto.bluzelle.curium.crud.CrudValue>} value
 * @return {!proto.bluzelle.curium.crud.QueryAllCrudValueResponse} returns this
*/
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.prototype.setCrudvalueList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.bluzelle.curium.crud.CrudValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bluzelle.curium.crud.CrudValue}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.prototype.addCrudvalue = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.bluzelle.curium.crud.CrudValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bluzelle.curium.crud.QueryAllCrudValueResponse} returns this
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.prototype.clearCrudvalueList = function() {
  return this.setCrudvalueList([]);
};


/**
 * optional cosmos.base.query.v1beta1.PageResponse pagination = 2;
 * @return {?proto.cosmos.base.query.v1beta1.PageResponse}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.prototype.getPagination = function() {
  return /** @type{?proto.cosmos.base.query.v1beta1.PageResponse} */ (
    jspb.Message.getWrapperField(this, cosmos_base_query_v1beta1_pagination_pb.PageResponse, 2));
};


/**
 * @param {?proto.cosmos.base.query.v1beta1.PageResponse|undefined} value
 * @return {!proto.bluzelle.curium.crud.QueryAllCrudValueResponse} returns this
*/
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bluzelle.curium.crud.QueryAllCrudValueResponse} returns this
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bluzelle.curium.crud.QueryAllCrudValueResponse.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.bluzelle.curium.crud);
