// source: nft/query.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var cosmos_base_query_v1beta1_pagination_pb = require('../cosmos/base/query/v1beta1/pagination_pb.js');
goog.object.extend(proto, cosmos_base_query_v1beta1_pagination_pb);
var nft_nft_pb = require('../nft/nft_pb.js');
goog.object.extend(proto, nft_nft_pb);
goog.exportSymbol('proto.bluzelle.curium.nft.QueryAllNftRequest', null, global);
goog.exportSymbol('proto.bluzelle.curium.nft.QueryAllNftResponse', null, global);
goog.exportSymbol('proto.bluzelle.curium.nft.QueryGetNftRequest', null, global);
goog.exportSymbol('proto.bluzelle.curium.nft.QueryGetNftResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bluzelle.curium.nft.QueryGetNftRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bluzelle.curium.nft.QueryGetNftRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bluzelle.curium.nft.QueryGetNftRequest.displayName = 'proto.bluzelle.curium.nft.QueryGetNftRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bluzelle.curium.nft.QueryGetNftResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bluzelle.curium.nft.QueryGetNftResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bluzelle.curium.nft.QueryGetNftResponse.displayName = 'proto.bluzelle.curium.nft.QueryGetNftResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bluzelle.curium.nft.QueryAllNftRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.bluzelle.curium.nft.QueryAllNftRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bluzelle.curium.nft.QueryAllNftRequest.displayName = 'proto.bluzelle.curium.nft.QueryAllNftRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.bluzelle.curium.nft.QueryAllNftResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.bluzelle.curium.nft.QueryAllNftResponse.repeatedFields_, null);
};
goog.inherits(proto.bluzelle.curium.nft.QueryAllNftResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.bluzelle.curium.nft.QueryAllNftResponse.displayName = 'proto.bluzelle.curium.nft.QueryAllNftResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bluzelle.curium.nft.QueryGetNftRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.bluzelle.curium.nft.QueryGetNftRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bluzelle.curium.nft.QueryGetNftRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.nft.QueryGetNftRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bluzelle.curium.nft.QueryGetNftRequest}
 */
proto.bluzelle.curium.nft.QueryGetNftRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bluzelle.curium.nft.QueryGetNftRequest;
  return proto.bluzelle.curium.nft.QueryGetNftRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bluzelle.curium.nft.QueryGetNftRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bluzelle.curium.nft.QueryGetNftRequest}
 */
proto.bluzelle.curium.nft.QueryGetNftRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bluzelle.curium.nft.QueryGetNftRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bluzelle.curium.nft.QueryGetNftRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bluzelle.curium.nft.QueryGetNftRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.nft.QueryGetNftRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
};


/**
 * optional uint32 id = 1;
 * @return {number}
 */
proto.bluzelle.curium.nft.QueryGetNftRequest.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.bluzelle.curium.nft.QueryGetNftRequest} returns this
 */
proto.bluzelle.curium.nft.QueryGetNftRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bluzelle.curium.nft.QueryGetNftResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bluzelle.curium.nft.QueryGetNftResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bluzelle.curium.nft.QueryGetNftResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.nft.QueryGetNftResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    nft: (f = msg.getNft()) && nft_nft_pb.Nft.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bluzelle.curium.nft.QueryGetNftResponse}
 */
proto.bluzelle.curium.nft.QueryGetNftResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bluzelle.curium.nft.QueryGetNftResponse;
  return proto.bluzelle.curium.nft.QueryGetNftResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bluzelle.curium.nft.QueryGetNftResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bluzelle.curium.nft.QueryGetNftResponse}
 */
proto.bluzelle.curium.nft.QueryGetNftResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new nft_nft_pb.Nft;
      reader.readMessage(value,nft_nft_pb.Nft.deserializeBinaryFromReader);
      msg.setNft(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bluzelle.curium.nft.QueryGetNftResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bluzelle.curium.nft.QueryGetNftResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bluzelle.curium.nft.QueryGetNftResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.nft.QueryGetNftResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNft();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      nft_nft_pb.Nft.serializeBinaryToWriter
    );
  }
};


/**
 * optional Nft Nft = 1;
 * @return {?proto.bluzelle.curium.nft.Nft}
 */
proto.bluzelle.curium.nft.QueryGetNftResponse.prototype.getNft = function() {
  return /** @type{?proto.bluzelle.curium.nft.Nft} */ (
    jspb.Message.getWrapperField(this, nft_nft_pb.Nft, 1));
};


/**
 * @param {?proto.bluzelle.curium.nft.Nft|undefined} value
 * @return {!proto.bluzelle.curium.nft.QueryGetNftResponse} returns this
*/
proto.bluzelle.curium.nft.QueryGetNftResponse.prototype.setNft = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bluzelle.curium.nft.QueryGetNftResponse} returns this
 */
proto.bluzelle.curium.nft.QueryGetNftResponse.prototype.clearNft = function() {
  return this.setNft(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bluzelle.curium.nft.QueryGetNftResponse.prototype.hasNft = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bluzelle.curium.nft.QueryAllNftRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.bluzelle.curium.nft.QueryAllNftRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bluzelle.curium.nft.QueryAllNftRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.nft.QueryAllNftRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    pagination: (f = msg.getPagination()) && cosmos_base_query_v1beta1_pagination_pb.PageRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bluzelle.curium.nft.QueryAllNftRequest}
 */
proto.bluzelle.curium.nft.QueryAllNftRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bluzelle.curium.nft.QueryAllNftRequest;
  return proto.bluzelle.curium.nft.QueryAllNftRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bluzelle.curium.nft.QueryAllNftRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bluzelle.curium.nft.QueryAllNftRequest}
 */
proto.bluzelle.curium.nft.QueryAllNftRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new cosmos_base_query_v1beta1_pagination_pb.PageRequest;
      reader.readMessage(value,cosmos_base_query_v1beta1_pagination_pb.PageRequest.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bluzelle.curium.nft.QueryAllNftRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bluzelle.curium.nft.QueryAllNftRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bluzelle.curium.nft.QueryAllNftRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.nft.QueryAllNftRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      cosmos_base_query_v1beta1_pagination_pb.PageRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional cosmos.base.query.v1beta1.PageRequest pagination = 1;
 * @return {?proto.cosmos.base.query.v1beta1.PageRequest}
 */
proto.bluzelle.curium.nft.QueryAllNftRequest.prototype.getPagination = function() {
  return /** @type{?proto.cosmos.base.query.v1beta1.PageRequest} */ (
    jspb.Message.getWrapperField(this, cosmos_base_query_v1beta1_pagination_pb.PageRequest, 1));
};


/**
 * @param {?proto.cosmos.base.query.v1beta1.PageRequest|undefined} value
 * @return {!proto.bluzelle.curium.nft.QueryAllNftRequest} returns this
*/
proto.bluzelle.curium.nft.QueryAllNftRequest.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bluzelle.curium.nft.QueryAllNftRequest} returns this
 */
proto.bluzelle.curium.nft.QueryAllNftRequest.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bluzelle.curium.nft.QueryAllNftRequest.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.bluzelle.curium.nft.QueryAllNftResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.bluzelle.curium.nft.QueryAllNftResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.bluzelle.curium.nft.QueryAllNftResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.bluzelle.curium.nft.QueryAllNftResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.nft.QueryAllNftResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    nftList: jspb.Message.toObjectList(msg.getNftList(),
    nft_nft_pb.Nft.toObject, includeInstance),
    pagination: (f = msg.getPagination()) && cosmos_base_query_v1beta1_pagination_pb.PageResponse.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.bluzelle.curium.nft.QueryAllNftResponse}
 */
proto.bluzelle.curium.nft.QueryAllNftResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.bluzelle.curium.nft.QueryAllNftResponse;
  return proto.bluzelle.curium.nft.QueryAllNftResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.bluzelle.curium.nft.QueryAllNftResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.bluzelle.curium.nft.QueryAllNftResponse}
 */
proto.bluzelle.curium.nft.QueryAllNftResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new nft_nft_pb.Nft;
      reader.readMessage(value,nft_nft_pb.Nft.deserializeBinaryFromReader);
      msg.addNft(value);
      break;
    case 2:
      var value = new cosmos_base_query_v1beta1_pagination_pb.PageResponse;
      reader.readMessage(value,cosmos_base_query_v1beta1_pagination_pb.PageResponse.deserializeBinaryFromReader);
      msg.setPagination(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.bluzelle.curium.nft.QueryAllNftResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.bluzelle.curium.nft.QueryAllNftResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.bluzelle.curium.nft.QueryAllNftResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.bluzelle.curium.nft.QueryAllNftResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNftList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      nft_nft_pb.Nft.serializeBinaryToWriter
    );
  }
  f = message.getPagination();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      cosmos_base_query_v1beta1_pagination_pb.PageResponse.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Nft Nft = 1;
 * @return {!Array<!proto.bluzelle.curium.nft.Nft>}
 */
proto.bluzelle.curium.nft.QueryAllNftResponse.prototype.getNftList = function() {
  return /** @type{!Array<!proto.bluzelle.curium.nft.Nft>} */ (
    jspb.Message.getRepeatedWrapperField(this, nft_nft_pb.Nft, 1));
};


/**
 * @param {!Array<!proto.bluzelle.curium.nft.Nft>} value
 * @return {!proto.bluzelle.curium.nft.QueryAllNftResponse} returns this
*/
proto.bluzelle.curium.nft.QueryAllNftResponse.prototype.setNftList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.bluzelle.curium.nft.Nft=} opt_value
 * @param {number=} opt_index
 * @return {!proto.bluzelle.curium.nft.Nft}
 */
proto.bluzelle.curium.nft.QueryAllNftResponse.prototype.addNft = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.bluzelle.curium.nft.Nft, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.bluzelle.curium.nft.QueryAllNftResponse} returns this
 */
proto.bluzelle.curium.nft.QueryAllNftResponse.prototype.clearNftList = function() {
  return this.setNftList([]);
};


/**
 * optional cosmos.base.query.v1beta1.PageResponse pagination = 2;
 * @return {?proto.cosmos.base.query.v1beta1.PageResponse}
 */
proto.bluzelle.curium.nft.QueryAllNftResponse.prototype.getPagination = function() {
  return /** @type{?proto.cosmos.base.query.v1beta1.PageResponse} */ (
    jspb.Message.getWrapperField(this, cosmos_base_query_v1beta1_pagination_pb.PageResponse, 2));
};


/**
 * @param {?proto.cosmos.base.query.v1beta1.PageResponse|undefined} value
 * @return {!proto.bluzelle.curium.nft.QueryAllNftResponse} returns this
*/
proto.bluzelle.curium.nft.QueryAllNftResponse.prototype.setPagination = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.bluzelle.curium.nft.QueryAllNftResponse} returns this
 */
proto.bluzelle.curium.nft.QueryAllNftResponse.prototype.clearPagination = function() {
  return this.setPagination(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.bluzelle.curium.nft.QueryAllNftResponse.prototype.hasPagination = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.bluzelle.curium.nft);
