// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: synchronizer/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetConfigRequest struct {
}

func (m *QueryGetConfigRequest) Reset()         { *m = QueryGetConfigRequest{} }
func (m *QueryGetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetConfigRequest) ProtoMessage()    {}
func (*QueryGetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08f2481f563f348d, []int{0}
}
func (m *QueryGetConfigRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetConfigRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetConfigRequest.Merge(m, src)
}
func (m *QueryGetConfigRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetConfigRequest proto.InternalMessageInfo

type QueryGetConfigResponse struct {
	Config *Config `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
}

func (m *QueryGetConfigResponse) Reset()         { *m = QueryGetConfigResponse{} }
func (m *QueryGetConfigResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetConfigResponse) ProtoMessage()    {}
func (*QueryGetConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08f2481f563f348d, []int{1}
}
func (m *QueryGetConfigResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetConfigResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetConfigResponse.Merge(m, src)
}
func (m *QueryGetConfigResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetConfigResponse proto.InternalMessageInfo

func (m *QueryGetConfigResponse) GetConfig() *Config {
	if m != nil {
		return m.Config
	}
	return nil
}

type QueryGetSourceRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *QueryGetSourceRequest) Reset()         { *m = QueryGetSourceRequest{} }
func (m *QueryGetSourceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetSourceRequest) ProtoMessage()    {}
func (*QueryGetSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08f2481f563f348d, []int{2}
}
func (m *QueryGetSourceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSourceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSourceRequest.Merge(m, src)
}
func (m *QueryGetSourceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSourceRequest proto.InternalMessageInfo

func (m *QueryGetSourceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type QueryGetSourceResponse struct {
	Source *Source `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
}

func (m *QueryGetSourceResponse) Reset()         { *m = QueryGetSourceResponse{} }
func (m *QueryGetSourceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetSourceResponse) ProtoMessage()    {}
func (*QueryGetSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08f2481f563f348d, []int{3}
}
func (m *QueryGetSourceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetSourceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetSourceResponse.Merge(m, src)
}
func (m *QueryGetSourceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetSourceResponse proto.InternalMessageInfo

func (m *QueryGetSourceResponse) GetSource() *Source {
	if m != nil {
		return m.Source
	}
	return nil
}

type QueryAllSourceRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSourceRequest) Reset()         { *m = QueryAllSourceRequest{} }
func (m *QueryAllSourceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllSourceRequest) ProtoMessage()    {}
func (*QueryAllSourceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_08f2481f563f348d, []int{4}
}
func (m *QueryAllSourceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSourceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSourceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSourceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSourceRequest.Merge(m, src)
}
func (m *QueryAllSourceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSourceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSourceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSourceRequest proto.InternalMessageInfo

func (m *QueryAllSourceRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllSourceResponse struct {
	Source     []*Source           `protobuf:"bytes,1,rep,name=Source,proto3" json:"Source,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllSourceResponse) Reset()         { *m = QueryAllSourceResponse{} }
func (m *QueryAllSourceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllSourceResponse) ProtoMessage()    {}
func (*QueryAllSourceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_08f2481f563f348d, []int{5}
}
func (m *QueryAllSourceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllSourceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllSourceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllSourceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllSourceResponse.Merge(m, src)
}
func (m *QueryAllSourceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllSourceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllSourceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllSourceResponse proto.InternalMessageInfo

func (m *QueryAllSourceResponse) GetSource() []*Source {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *QueryAllSourceResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetConfigRequest)(nil), "bluzelle.curium.synchronizer.QueryGetConfigRequest")
	proto.RegisterType((*QueryGetConfigResponse)(nil), "bluzelle.curium.synchronizer.QueryGetConfigResponse")
	proto.RegisterType((*QueryGetSourceRequest)(nil), "bluzelle.curium.synchronizer.QueryGetSourceRequest")
	proto.RegisterType((*QueryGetSourceResponse)(nil), "bluzelle.curium.synchronizer.QueryGetSourceResponse")
	proto.RegisterType((*QueryAllSourceRequest)(nil), "bluzelle.curium.synchronizer.QueryAllSourceRequest")
	proto.RegisterType((*QueryAllSourceResponse)(nil), "bluzelle.curium.synchronizer.QueryAllSourceResponse")
}

func init() { proto.RegisterFile("synchronizer/query.proto", fileDescriptor_08f2481f563f348d) }

var fileDescriptor_08f2481f563f348d = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xc1, 0x8a, 0x13, 0x31,
	0x18, 0xc7, 0x9b, 0x75, 0x5d, 0xd8, 0x78, 0x0b, 0xa8, 0x6b, 0x59, 0x06, 0x19, 0x96, 0x2a, 0x56,
	0x13, 0xda, 0x7a, 0xf4, 0x52, 0x05, 0x8b, 0x37, 0xad, 0xe0, 0xc1, 0x8b, 0x64, 0x86, 0x38, 0x1d,
	0xc8, 0x24, 0xd3, 0x49, 0x46, 0x6c, 0x45, 0x10, 0x9f, 0x40, 0xf0, 0x01, 0xbc, 0x78, 0xf0, 0x51,
	0x3c, 0x16, 0xbc, 0x78, 0x94, 0xd6, 0x07, 0x91, 0x26, 0x19, 0x3b, 0xd3, 0x0e, 0xdd, 0xe9, 0x6d,
	0x48, 0xbe, 0xff, 0xff, 0xfb, 0x4d, 0xfe, 0xf9, 0x02, 0xcf, 0xd4, 0x4c, 0x84, 0x93, 0x4c, 0x8a,
	0x78, 0xce, 0x32, 0x32, 0xcd, 0x59, 0x36, 0xc3, 0x69, 0x26, 0xb5, 0x44, 0xe7, 0x01, 0xcf, 0xe7,
	0x8c, 0x73, 0x86, 0xc3, 0x3c, 0x8b, 0xf3, 0x04, 0x97, 0x2b, 0xdb, 0xe7, 0x91, 0x94, 0x11, 0x67,
	0x84, 0xa6, 0x31, 0xa1, 0x42, 0x48, 0x4d, 0x75, 0x2c, 0x85, 0xb2, 0xda, 0xf6, 0xbd, 0x50, 0xaa,
	0x44, 0x2a, 0x12, 0x50, 0xc5, 0xac, 0x29, 0x79, 0xd7, 0x0b, 0x98, 0xa6, 0x3d, 0x92, 0xd2, 0x28,
	0x16, 0xa6, 0xd8, 0xd5, 0xde, 0xaa, 0x10, 0x28, 0x99, 0x67, 0x21, 0xab, 0xdd, 0x0a, 0xa5, 0x78,
	0x1b, 0x47, 0x76, 0xcb, 0xbf, 0x09, 0xaf, 0xbf, 0x58, 0xfb, 0x8e, 0x98, 0x7e, 0x62, 0xd6, 0xc7,
	0x6c, 0x9a, 0x33, 0xa5, 0xfd, 0x57, 0xf0, 0xc6, 0xf6, 0x86, 0x4a, 0xa5, 0x50, 0x0c, 0x3d, 0x82,
	0x27, 0x76, 0xe5, 0x0c, 0xdc, 0x06, 0x77, 0xaf, 0xf5, 0x2f, 0xf0, 0xbe, 0x3f, 0xc4, 0x4e, 0xed,
	0x34, 0x7e, 0x77, 0xd3, 0xf0, 0xa5, 0x61, 0x74, 0x0d, 0x11, 0x82, 0xc7, 0x82, 0x26, 0xcc, 0x98,
	0x9e, 0x8e, 0xcd, 0x77, 0x19, 0xa2, 0x28, 0xde, 0x40, 0xd8, 0x95, 0x66, 0x10, 0x4e, 0xed, 0x34,
	0xfe, 0x1b, 0x07, 0x31, 0xe4, 0xbc, 0x0a, 0xf1, 0x14, 0xc2, 0xcd, 0xc1, 0x3a, 0xeb, 0x0e, 0xb6,
	0x29, 0xe0, 0x75, 0x0a, 0xd8, 0x46, 0xeb, 0x52, 0xc0, 0xcf, 0x69, 0x54, 0x68, 0xc7, 0x25, 0xa5,
	0xff, 0x0d, 0x38, 0xf2, 0x52, 0x87, 0x1a, 0xf2, 0x2b, 0x87, 0x92, 0xa3, 0x51, 0x05, 0xf0, 0xc8,
	0x00, 0xde, 0xb9, 0x14, 0xd0, 0xb6, 0x2e, 0x13, 0xf6, 0x3f, 0x1d, 0xc3, 0xab, 0x86, 0x10, 0xfd,
	0x00, 0x05, 0x11, 0x1a, 0xec, 0x67, 0xa9, 0x0d, 0xae, 0xfd, 0xf0, 0x30, 0x91, 0x65, 0xf1, 0x07,
	0x9f, 0x7f, 0xfd, 0xfd, 0x7a, 0xf4, 0x00, 0x75, 0x49, 0xa1, 0x26, 0x56, 0x4d, 0x6a, 0xee, 0x31,
	0xf9, 0xb0, 0xbe, 0x0e, 0x1f, 0xd1, 0x77, 0x00, 0x4f, 0xad, 0xcf, 0x90, 0xf3, 0x46, 0xb4, 0xdb,
	0x09, 0x37, 0xa2, 0xdd, 0x09, 0xcd, 0xbf, 0x6f, 0x68, 0x3b, 0xe8, 0xa2, 0x09, 0xad, 0xc1, 0xfc,
	0x3f, 0x37, 0x4d, 0x0f, 0xb5, 0x32, 0x7e, 0x4d, 0x0f, 0xb5, 0x3a, 0x9a, 0x4d, 0x31, 0xed, 0x0b,
	0xf0, 0xf8, 0xd9, 0xcf, 0xa5, 0x07, 0x16, 0x4b, 0x0f, 0xfc, 0x59, 0x7a, 0xe0, 0xcb, 0xca, 0x6b,
	0x2d, 0x56, 0x5e, 0xeb, 0xf7, 0xca, 0x6b, 0xbd, 0x26, 0x51, 0xac, 0x27, 0x79, 0x80, 0x43, 0x99,
	0xec, 0x38, 0xbd, 0xaf, 0x7a, 0xe9, 0x59, 0xca, 0x54, 0x70, 0x62, 0x5e, 0x93, 0xc1, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x0c, 0xfc, 0x14, 0x2c, 0x07, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	Source(ctx context.Context, in *QueryGetSourceRequest, opts ...grpc.CallOption) (*QueryGetSourceResponse, error)
	SourceAll(ctx context.Context, in *QueryAllSourceRequest, opts ...grpc.CallOption) (*QueryAllSourceResponse, error)
	GetConfig(ctx context.Context, in *QueryGetConfigRequest, opts ...grpc.CallOption) (*QueryGetConfigResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Source(ctx context.Context, in *QueryGetSourceRequest, opts ...grpc.CallOption) (*QueryGetSourceResponse, error) {
	out := new(QueryGetSourceResponse)
	err := c.cc.Invoke(ctx, "/bluzelle.curium.synchronizer.Query/Source", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SourceAll(ctx context.Context, in *QueryAllSourceRequest, opts ...grpc.CallOption) (*QueryAllSourceResponse, error) {
	out := new(QueryAllSourceResponse)
	err := c.cc.Invoke(ctx, "/bluzelle.curium.synchronizer.Query/SourceAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetConfig(ctx context.Context, in *QueryGetConfigRequest, opts ...grpc.CallOption) (*QueryGetConfigResponse, error) {
	out := new(QueryGetConfigResponse)
	err := c.cc.Invoke(ctx, "/bluzelle.curium.synchronizer.Query/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	Source(context.Context, *QueryGetSourceRequest) (*QueryGetSourceResponse, error)
	SourceAll(context.Context, *QueryAllSourceRequest) (*QueryAllSourceResponse, error)
	GetConfig(context.Context, *QueryGetConfigRequest) (*QueryGetConfigResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Source(ctx context.Context, req *QueryGetSourceRequest) (*QueryGetSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Source not implemented")
}
func (*UnimplementedQueryServer) SourceAll(ctx context.Context, req *QueryAllSourceRequest) (*QueryAllSourceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SourceAll not implemented")
}
func (*UnimplementedQueryServer) GetConfig(ctx context.Context, req *QueryGetConfigRequest) (*QueryGetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Source_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Source(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bluzelle.curium.synchronizer.Query/Source",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Source(ctx, req.(*QueryGetSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SourceAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SourceAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bluzelle.curium.synchronizer.Query/SourceAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SourceAll(ctx, req.(*QueryAllSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bluzelle.curium.synchronizer.Query/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetConfig(ctx, req.(*QueryGetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "bluzelle.curium.synchronizer.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Source",
			Handler:    _Query_Source_Handler,
		},
		{
			MethodName: "SourceAll",
			Handler:    _Query_SourceAll_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Query_GetConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "synchronizer/query.proto",
}

func (m *QueryGetConfigRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetConfigRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetConfigRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetConfigResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetConfigResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetConfigResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Config != nil {
		{
			size, err := m.Config.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSourceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSourceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSourceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetSourceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetSourceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetSourceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Source != nil {
		{
			size, err := m.Source.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSourceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSourceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSourceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllSourceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllSourceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllSourceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Source) > 0 {
		for iNdEx := len(m.Source) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Source[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetConfigRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetConfigResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Config != nil {
		l = m.Config.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSourceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetSourceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Source != nil {
		l = m.Source.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSourceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllSourceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Source) > 0 {
		for _, e := range m.Source {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetConfigRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetConfigRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetConfigRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetConfigResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetConfigResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetConfigResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Config", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Config == nil {
				m.Config = &Config{}
			}
			if err := m.Config.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSourceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSourceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSourceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetSourceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetSourceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetSourceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Source == nil {
				m.Source = &Source{}
			}
			if err := m.Source.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSourceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSourceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSourceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllSourceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllSourceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllSourceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = append(m.Source, &Source{})
			if err := m.Source[len(m.Source)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
